version: '3'

services:
  db:
    image: mariadb
    container_name: mariadb
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - ./mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=
    env_file:
      - db.env

  redis:
    image: redis:alpine
    container_name: redis
    restart: always

  nextcloud_fpm:
    image: nextcloud:fpm-alpine
    container_name: nextcloud_fpm
    restart: always
    volumes:
      - ./nextcloud:/var/www/html
    environment:
      - MYSQL_HOST=db
      - REDIS_HOST=redis
    env_file:
      - db.env
    depends_on:
      - db
      - redis

  nextcloud_nginx:
    build: ./nginx
    container_name: nextcloud_nginx
    restart: always
    volumes:
      - ./nextcloud:/var/www/html:ro
    environment:
      - VIRTUAL_HOST=icgarsas8yis6ivm.myfritz.net
      - LETSENCRYPT_HOST=icgarsas8yis6ivm.myfritz.net
      - LETSENCRYPT_EMAIL=josua_koenig@icloud.com
    depends_on:
      - nextcloud_fpm
    networks:
      - proxy-tier
      - default

  nextcloud_cron:
    image: nextcloud:fpm-alpine
    container_name: nextcloud_cron
    restart: always
    volumes:
      - ./nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis

  proxy:
    build: ./proxy
    container_name: proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - ./certs:/etc/nginx/certs:ro
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-tier

  letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    restart: always
    volumes:
      - ./certs:/etc/nginx/certs
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy-tier
    depends_on:
      - proxy

  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: always
    command: -H unix:///var/run/docker.sock
    ports:
      - 9001:9000
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer/:/data

  adminer:
    build: ./adminer/.
    container_name: adminer
    restart: always
    ports:
      - '8181:8080'
    environment:
      PMA_HOST: maria-db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    links:
      - maria-db

  factorio-server-manager:
    image: majormjr/factorio-server-manager
    container_name: factorio-server-manager
    restart: always
    ports: 
      - '88:80'
      - '443:443'
      - '34197:34197'
    volumes:
      - /factorio/saves:/opt/factorio/saves
      - /factorio/mods:/opt/factorio/mods
      - /factorio/config:/opt/factorio/config
      - /security:/security

networks:
  proxy-tier: